apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pokeapi

resources:
- kanto/
- johto/


generatorOptions:
  disableNameSuffixHash: false ##Obligé pour qu'elle soit iso avec le nom de la config map attendu sinon ça rajoute du hachage
                              ##(Potentiellement faire en sorte qu'on attende une configmap avec hachage ?)

configMapGenerator:
- name: pokedex-kanto-cm
  literals:
    - POKEDEX_NAME="Kanto"
    - POKEDEX_START_NUMBER="1"
    - POKEDEX_END_NUMBER="151"

- name: pokedex-johto-cm
  files:
    - ./johto/application.properties
  envs:
    - ./johto/.env